steps:
  - name: Baixar o código
    uses: actions/checkout@v4

  - name: Criar arquivo .env dinamicamente
    run: |
      echo "MINHA_SENHA_API=${{ secrets.SENHA_API_EMAIL }}" > .env

  - name: Rodar meu projeto
    run: pnpm dev
