name: Workflow pnpm

on: [push]

jobs:
  iniciar-projeto:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Criar arquivo .env
        run: |
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env

      - name: Instalar dependências
        run: pnpm install

      - name: Subir servidor em background
        run: pnpm dev &

      - name: Esperar servidor ficar pronto
        run: npx wait-on http://localhost:3000

      - name: Testar rota de envio de email
        run: |
          curl -f -X POST http://localhost:3000/api/enviar-email \
            -H "Content-Type: application/json" \
            -d '{"emailUsuario": "gamestavinho4@gmail.com", "userName": "Otávio"}'
