name: Workflow pnpm

on: [push]

jobs:
  iniciar-projeto:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Criar arquivo .env dinamicamente
        run: |
          echo "EMAIL_PASSWORD=${{ secrets.SENHA_API_EMAIL }}" > .env

      - name: Verificar se o arquivo foi criado
        run: |
          echo "Lendo o conteúdo do arquivo .env:"
          cat .env
