name: Workflow pnpm

on: [push]

jobs:
  iniciar-projeto:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Criar arquivo .env
        run: |
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env

      - name: Instalar dependências
        run: pnpm install

      - name: Iniciar projeto
        run: pnpm dev
